public inherited sharing class AccountTriggerHandler {
  /*
  public static void onBeforeInsert(
    List<Account> newAccountList,
    Map<Id, Account> newAccountMap
  ) {
    for (Account newAccount : newAccountList) {
      if (newAccount.Phone == null) {
        newAccount.addError('Por favor, informe um telefone');
      } else {
        AccountTriggerHelper.formatPhone(newAccount);
      }
    }
  }*/
}